name: Compile Reels

on:
  workflow_dispatch:  # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      
      - name: Run Compilation Script
        run: |
          ls -l ./hiddenmemoriz/reels
