name: Upload Spotify PNG to GDrive

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rclone
        run: sudo apt-get install -y rclone

      - name: Setup Service Account File
        run: |
          echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT }}' > sa.json

      - name: Upload to Specific Folder
        env:
          # Configuration via environment variables
          RCLONE_CONFIG_MYDRIVE_TYPE: drive
          RCLONE_CONFIG_MYDRIVE_SCOPE: drive
          RCLONE_CONFIG_MYDRIVE_SERVICE_ACCOUNT_FILE: sa.json
        run: |
          rclone copy spotify.png mydrive: \
          --drive-root-folder-id "1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH" \
          --drive-use-trash=false \
          -v
