name: Test Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          sudo apt update
          sudo apt install -y unzip curl
          curl https://rclone.org/install.sh | sudo bash

      - name: Setup rclone with service account
        run: |
          mkdir -p ~/.config/rclone
          printf '%s' "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" > ~/service_account.json
          rclone config create gdrive drive scope drive.file service_account_file ~/service_account.json

      - name: Upload spotify.png to Drive
        run: |
          rclone copy spotify.png gdrive:1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH/ -P
