name: Download Drive Folder (No Auth)

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install gdown
        run: pip install gdown

      - name: Download folder
        run: |
          mkdir -p reels

          # Replace with your folder link
          gdown --folder https://drive.google.com/drive/folders/1520FEU7czB97tS9da1UfrrZXdUdwyjYv -O assets/drive-files

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add assets/drive-files
          git commit -m "Download Drive folder" || echo "No changes"
          git push
