name: Sync Drive Folder to Repo

on:
  workflow_dispatch:   # run manually
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (optional)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONFIG }}' > ~/.config/rclone/rclone.conf

      - name: Sync Drive folder
        run: |
          mkdir -p reels

          # Replace YOUR_FOLDER_ID
          rclone sync mydrive:1520FEU7czB97tS9da1UfrrZXdUdwyjYv assets/drive-files --progress

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add assets/drive-files
          git commit -m "Sync Drive folder" || echo "No changes"
          git push
